### ISSUE TITLE
........

### ISSUE THREAD

**Issue by BaraPellumb** [lucadentella/irrighino#2]

**Comment by lucadentella** [comment]
Hi, I wrote a [blog post](http://www.lucadentella.it/2019/02/02/irrighino-e-yun-rev-2/) about running Irrighino on newer Yuns. Please check if it solves your problems

**Comment by BaraPellumb** [comment]
thanks but this won't help me/does not apply to me as using an old yun with
upgraded version (2017)  ...

(removed connections and testing the just outputs on the arduino they seam
to be stuck on high (4.5v) no matter the commands -  it failing to
communicate when on manual (it still does some rain sensor update (table
update logs)  but fails to deliver any HI/ LOW .

not sure about this line: f(analogValue < 100) actualStatus =
SWITCH_MANUAL_OFF;   changing it to == and one error goes away!

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by lucadentella** [comment]
Hi
```
if(analogValue < 100) actualStatus = SWITCH_MANUAL_OFF;
```
this line is because of I'm reading all the switches with only one analog pin using a chain of resistors. Based on the position of the switches, the analog value will be in different ranges... 
You wrote that if you put "==" it works... I suspect it's because it will never match the condition so you'll never be able to set it to manual off.
```

**Comment by BaraPellumb** [comment]
Thanks for your time and valued advice. I can not see a server connection
link before the yun server connection checks anywhere in the sketch.  (had
tested the behavior  based on the old code ) and the conditions set for
analog status read make it impossible to test without feeding any analogue
inputs. In other words activating the outputs for testing it on the bench
with a meter seam to be impossible.
 I need to get my head around how it works but basically reading bytes from
the slide may be the problem - how does it know without setting it to high
or low first it must be an if == somewhere to test so then to write the
outputs.


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
